name: Generate cover letter

on:
  workflow_dispatch:
    inputs:
      customInput:
        description: 'cover letter for which company'
        required: true
        default: 'default-value'
        type: string

jobs:
  run-script:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run script with custom input
        run: |
          pip3 install --use-pep517 --break-system-packages -r requirements.txt
          python3 chatbot.py
