name: Generate cover letter

on:
  workflow_dispatch:
    inputs:
      company:
        description: 'cover letter for which company'
        required: true
        type: string
      jobDescription:
        description: 'job description'
        required: true
        type: string

jobs:
  run-script:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Run script with custom input
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pip3 install --use-pep517 --break-system-packages -r requirements.txt
          python3 chatbot.py "${{ github.event.inputs.jobDescription }}"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.customInput }}
          path: cover-letter.docx
          compression-level: 0
